/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author home
 */

public class stopwatchz extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public stopwatchz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hrs = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        mins = new javax.swing.JLabel();
        mele = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        strbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        hrs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hrs.setText("0");
        jPanel2.add(hrs);
        hrs.setBounds(10, 10, 40, 14);

        sec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sec.setText("0");
        jPanel2.add(sec);
        sec.setBounds(100, 10, 30, 20);

        mins.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mins.setText("0");
        jPanel2.add(mins);
        mins.setBounds(50, 10, 30, 22);

        mele.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mele.setForeground(new java.awt.Color(255, 51, 51));
        mele.setText("0");
        jPanel2.add(mele);
        mele.setBounds(154, 10, 40, 20);

        jLabel3.setText("sec");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 20, 20, 14);

        jLabel6.setText("mins");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 20, 34, 14);

        jLabel7.setText("hr");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 20, 20, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 30, 200, 40);

        strbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        strbtn.setText("START");
        strbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                strbtnMouseClicked(evt);
            }
        });
        strbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                strbtnKeyPressed(evt);
            }
        });
        jPanel1.add(strbtn);
        strbtn.setBounds(50, 80, 70, 23);

        console.setEditable(false);
        console.setBackground(new java.awt.Color(0, 0, 0));
        console.setColumns(20);
        console.setForeground(new java.awt.Color(51, 153, 0));
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 230, 90);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logs");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 40, 14);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click here to save the  logs");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 230, 150, 14);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Guide here");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 230, 70, 14);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clear Logs");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 110, 70, 14);

        lap.setText("Reset");
        lap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapMouseClicked(evt);
            }
        });
        jPanel1.add(lap);
        lap.setBounds(150, 80, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static final DecimalFormat df = new DecimalFormat("0.00");
private static final DecimalFormat S = new DecimalFormat("0");
private static final DecimalFormat dx = new DecimalFormat("0.0000");
   private volatile boolean running = true;
    private volatile boolean paused = false;
    private final Object pauseLock = new Object();
int i = 0;
int s = 0;
int hr = 0;
int ml = 0;
int m = 0;
int start = 0;
int started = 0;
int pause = 0;
int run  = 0;
int res = 0;
int reset = 0;
int laps = 0;
int lapx = 0;
        
     mythread thread = new mythread();
    private void strbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strbtnKeyPressed
       
    }//GEN-LAST:event_strbtnKeyPressed

    private void strbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strbtnMouseClicked
 start = 1;
        if(start == 1 && started == 0){
            strbtn.setText("Pause");
            lap.setText("Lap");
            thread.start();
            reset = 0;
            run = 1;
            started = 1;
            laps = 1;
        }else if(run == 1 && start == 1){
            pause = 1;
             strbtn.setText("Start");
             lap.setText("Reset");
             reset = 1;
            run = 0;
            laps = 0;

            
        }else if(pause == 1){
           pause = 0;
           res = 1;
           strbtn.setText("Pause");
            lap.setText("Lap");
            reset = 0;
            laps = 1;
            
        }else if(res == 1){
            run = 1;
            start = 1;
            res = 0;
            laps = 1;
            
            strbtn.setText("Pause");
            lap.setText("Lap");
            reset = 0;
        }
            
      
      
    }//GEN-LAST:event_strbtnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

 try {
                FileWriter output = new FileWriter("stopwatch.datzineini");
                output.write(console.getText());
                output.close();
                  Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "LOG SAVED",
    "Sucess",
    JOptionPane.OK_OPTION);
                
            } catch (Exception e) {
                System.out.println("File not Found");
            }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
          guide x= new guide();

   x.setVisible(true);

    this.setVisible(false);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       console.setText("stopwatch 2.0 by cyberx");
        console.append("\n Log Cleared\n"); 
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void lapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapMouseClicked
     String hrss = hrs.getText();
     String minss = mins.getText();
     String secss = sec.getText();
        if(reset == 1 && laps == 0){
        i = 0;
s = 0;
hr = 0;
ml = 0;
 m = 0;
 lapx = 0;
 String ss =  String.valueOf(s);
 String hhr =  String.valueOf(hr);
 String mml =  String.valueOf(ml);
 String mmm =  String.valueOf(m);
  hrs.setText(hhr);
    mins.setText(mmm);
    sec.setText(ss);
    mele.setText(mml);
     }else if(laps == 1 && reset == 0){
         lapx++;
         console.append("Lap"+lapx+":"+hrss+"hrs,"+minss+"mins"+secss+"sec \n");
     }
    }//GEN-LAST:event_lapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopwatchz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopwatchz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopwatchz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopwatchz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopwatchz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea console;
    private javax.swing.JLabel hrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lap;
    private javax.swing.JLabel mele;
    private javax.swing.JLabel mins;
    private javax.swing.JLabel sec;
    private javax.swing.JButton strbtn;
    // End of variables declaration//GEN-END:variables
class mythread extends Thread
{
    @Override
    public void run()
    {
        
        
       
            try {
                while(true){
                   
                 if(pause == 1){
                     
                 }else{
                Thread.sleep(1);
                
                ml++;
                String mls =  String.valueOf(ml);
                mele.setText(mls);
                if(ml>1000){
                  s++;
                  ml = 0;
                   String seconds =  String.valueOf(s);
                sec.setText(seconds);
                }
                if(s>59)
                {
                   s =0;
                   m++;
                 String minute =  String.valueOf(m);
                mins.setText(minute);
                }
                if(m>59){
                        m =0;
                   hr++;
                 String hours =  String.valueOf(hr);
                hrs.setText(hours);
                }
            }
                }
            }catch (InterruptedException ex) {
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
    "Something went wrong?",
    "InterruptedException",
    JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        
    }

   
  
    
}

}

